"""add field

Revision ID: 258f0cb9b988
Revises: d71f45e389b2
Create Date: 2023-05-31 14:13:40.851477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '258f0cb9b988'
down_revision = 'd71f45e389b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise5')
    op.drop_table('exercise11')
    op.drop_table('exercise3')
    op.drop_table('exercise4')
    op.drop_table('exercise12')
    op.drop_table('exercise6')
    op.drop_table('exercise8')
    op.drop_table('exercise7')
    op.drop_table('exercise10')
    op.drop_table('exercise9')
    op.drop_table('exercise1')
    op.drop_table('exercise2')
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise1', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('exercise2', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('exercise3', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('exercise4', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('exercise5', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('exercise6', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('exercise7', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('exercise8', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('exercise9', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('exercise10', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('exercise11', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('exercise12', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('worker_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['worker_id'], ['id'])
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('worker_id')
        batch_op.drop_column('exercise12')
        batch_op.drop_column('exercise11')
        batch_op.drop_column('exercise10')
        batch_op.drop_column('exercise9')
        batch_op.drop_column('exercise8')
        batch_op.drop_column('exercise7')
        batch_op.drop_column('exercise6')
        batch_op.drop_column('exercise5')
        batch_op.drop_column('exercise4')
        batch_op.drop_column('exercise3')
        batch_op.drop_column('exercise2')
        batch_op.drop_column('exercise1')

    op.create_table('exercise2',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set3', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set4', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set5', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set6', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('excer2_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excer2_id'], ['workouts.id'], name='exercise2_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exercise1',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set3', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set4', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set5', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set6', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('excer1_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excer1_id'], ['workouts.id'], name='exercise1_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exercise9',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set3', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set4', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set5', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set6', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('excer9_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excer9_id'], ['workouts.id'], name='exercise9_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exercise10',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set3', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set4', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set5', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set6', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('excer10_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excer10_id'], ['workouts.id'], name='exercise10_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exercise7',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set3', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set4', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set5', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set6', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('excer7_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excer7_id'], ['workouts.id'], name='exercise7_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exercise8',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set3', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set4', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set5', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set6', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('excer8_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excer8_id'], ['workouts.id'], name='exercise8_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exercise6',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set3', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set4', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set5', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set6', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('excer6_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excer6_id'], ['workouts.id'], name='exercise6_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exercise12',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set3', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set4', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set5', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set6', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('excer12_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excer12_id'], ['workouts.id'], name='exercise12_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exercise4',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set3', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set4', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set5', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set6', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('excer4_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excer4_id'], ['workouts.id'], name='exercise4_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exercise3',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set3', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set4', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set5', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set6', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('excer3_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excer3_id'], ['workouts.id'], name='exercise3_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exercise11',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set3', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set4', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set5', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set6', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('excer11_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excer11_id'], ['workouts.id'], name='exercise11_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exercise5',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set3', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set4', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set5', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('set6', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('excer5_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excer5_id'], ['workouts.id'], name='exercise5_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
